ヒット＆ブローゲームに答えを表示する機能追加
konta3291/HitAndBlow pull request #10
Opened 2022-07-18 05:18 UTC by konta3291

#### ヒット＆ブローゲームに答えを表示する機能を追加しました。
不適切なところや、足りないところ、よりよい方法がありましたら教えて頂きたいです。
ご確認よろしくお願いします。

2022-07-18 05:27 UTC, Takatatsu9 commented
次の設定のどれかをやっておくと、PRがmergeされたときに
対応したIssueも自動Closeするのでやっておくと良いです。

- PRのタイトルに` resolve #Issue番号`を混ぜる
- コミットコメントに` resolve #Issue番号`を混ぜる
    - コミットハッシュを変えてforce-pushすると、都度Issue側に
    通知が行くらしいので修正いっぱいするつもりなら非推奨。
- 右のメニューにある`Development`から、対応するIssueを選択する

2022-07-18 05:30 UTC, konta3291 commented
かしこまりました、教えていただきありがとうございます。

2022-07-18 05:32 UTC, nabemasamasa reviewed
Done (はやい)

2022-07-18 05:32 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        Console.WriteLine()
[imo] ForEachしなくても、WriteLineの引数にCharの配列を渡してもOKのはず。

2022-07-18 05:41 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        Console.WriteLine()
ご指摘ありがとうございます。
試してみましたがコンソール画面に下記の文が表示されてしまいます。
 - System.Collections.Generic.List`1[System.Char]

配列ではなくListを使っているから、うまくいかないのかと考えています。

2022-07-18 05:42 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        Console.WriteLine()
そうですね。”配列”と私は言ってるので、Listは未確認です。

2022-07-18 05:48 UTC, Takatatsu9 requested changes
Done

2022-07-18 05:48 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
>      ''' <summary>
> branch-name: feat/ShowAnswer

[IMO/Q] あれ？ブランチ名は全部小文字でハイフン区切りって説明されてませんでしたっけ？

2022-07-18 05:48 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
>      ''' <summary>
[MUST] 起点ブランチが`master`になっていません。`master`起点にしてください。

2022-07-18 05:48 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +                ShowAnswer()
[IMO] ここでは正しい入力値かを判定して正しければ入力値を返すメソッドだと
見受けたんですけど、`ShowAnswer`ならそのまま返して、
文字列を表示することを責務としたメソッドで答えを表示してやればいいんじゃないですかね。

2022-07-18 06:01 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        Console.WriteLine()
Listを使う必要はなく、処理をよりシンプルに書きたいため配列を使う処理に変更します。

2022-07-18 06:06 UTC, konta3291 commented on HitAndBlow/HitAndBlowGame.vb
>      ''' <summary>
ご指摘ありがとうございます。
申し訳ないです。されたかもしれませんが忘れてしまっていました。
今後は絶対ないようにします。
ブランチ名を変えたいのですが、変えてPRを立て直した方がよろしいでしょうか。

2022-07-18 06:07 UTC, konta3291 commented on HitAndBlow/HitAndBlowGame.vb
>      ''' <summary>
ご指摘ありがとうございます。
かしこまりました、基点ブランチをmasterにします。

2022-07-18 06:08 UTC, konta3291 commented on HitAndBlow/Main.vb
> +                ShowAnswer()
ご指摘ありがとうございます。
かしこまりました、修正します。

2022-07-18 06:09 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
>      ''' <summary>
今回はこのままでいいです。PR立て直しはwipブランチじゃない場合はあんまりやってないことなので。

2022-07-18 06:23 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
>      ''' <summary>
一度 #4 も`feat/HitAndBlow`で見慣れない形式だったから、knowledgeへのリンクを添えてコメントしたんだけど、よく見たら「開発言語`VB.NET`を考慮し、**「小文字始まり大文字区切り」** でも良いとする」とも書いてあったんだよね……だとしても小文字始まりじゃないんだけど、、、(#4もそうだった、今気づいた……)

[git/作業ブランチ（topic branch）の命名ルール](https://github.com/daniel-software-tokyo/knowledge/blob/master/git/Git.beginner.md#%E4%BD%9C%E6%A5%AD%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81topic-branch%E3%81%AE%E5%91%BD%E5%90%8D%E3%83%AB%E3%83%BC%E3%83%AB)

2022-07-18 07:17 UTC, konta3291 commented
基点ブランチをmasterに変更しました。

2022-07-18 07:19 UTC, konta3291 commented on HitAndBlow/HitAndBlowGame.vb
>      ''' <summary>
基点ブランチをmasterにしました。
ご確認よろしくお願いします。

2022-07-18 07:48 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        Console.WriteLine()
配列に変更しました。
ご確認よろしくお願いします。コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/10/commits/4a5d5f059d33a7736621ad55e6801abcfd5ddf8e

2022-07-18 07:49 UTC, konta3291 commented on HitAndBlow/Main.vb
> +                ShowAnswer()
修正しました。
ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/10/commits/1ebddc0e71059b83b8a8586cb0eb555acdd38e21

2022-07-18 07:55 UTC, Takatatsu9 approved these changes
Done

2022-07-18 07:55 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +            Dim playerAnswer As String = Main.GetPlayerAnswer
Mainから呼んだHitAndBlowでMainの要素を呼ぶ…なんか嫌だな。

[IMO] そもそも`GetPlayerAnswer`の置き場所を変えるべきでは？

2022-07-18 07:55 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +                Main.ShowHitAndBlowResult(hit, blow)
そういえばこれもか

2022-07-18 07:55 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +            End If
[IMO] `If Not`のネスト内でクソ長ロジック書いたあとに`Else`で1行ポツンとあるのやだなー

2022-07-18 08:02 UTC, nabemasamasa reviewed
Done

2022-07-18 08:02 UTC, nabemasamasa commented on HitAndBlow/HitAndBlowGame.vb
> +            If Not "ShowAnswer".Equals(playerAnswer) Then
[imo]  `ShowAnswer`のIf文作ってShowAnswer呼んですぐ`Continue While`しちゃえば、If文でネストさせなくても良さそう。

2022-07-18 23:31 UTC, konta3291 commented on HitAndBlow/HitAndBlowGame.vb
> +            Dim playerAnswer As String = Main.GetPlayerAnswer
ご指摘ありがとうございます。
場所を置き換えました。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/10/commits/90a0f9f4bc493a3446ba5a2c362b2527bc125f1a
ご確認よろしくお願いします。

2022-07-18 23:32 UTC, konta3291 commented on HitAndBlow/HitAndBlowGame.vb
> +                Main.ShowHitAndBlowResult(hit, blow)
ご指摘ありがとうございます。
場所を置き換えました。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/10/commits/90a0f9f4bc493a3446ba5a2c362b2527bc125f1a
ご確認よろしくお願いします。

2022-07-18 23:33 UTC, konta3291 commented on HitAndBlow/HitAndBlowGame.vb
> +            End If
ご指摘ありがとうございます。
修正しました。
ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/10/commits/d3bedab3aac246af48eb7546da1acccd73be46ed

2022-07-18 23:33 UTC, konta3291 commented on HitAndBlow/HitAndBlowGame.vb
> +            If Not "ShowAnswer".Equals(playerAnswer) Then
ご指摘ありがとうございます。
修正しました。
ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/10/commits/d3bedab3aac246af48eb7546da1acccd73be46ed

2022-07-18 23:41 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +            Dim playerAnswer As String = Main.GetPlayerAnswer
直ってませんよ

2022-07-18 23:43 UTC, Takatatsu9 reviewed
Done

2022-07-18 23:43 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
>                  Dim blow As Integer = 0
インデント上げたまま放置？

2022-07-18 23:52 UTC, konta3291 commented on HitAndBlow/HitAndBlowGame.vb
>                  Dim blow As Integer = 0
申し訳ありません。放置してしまっていました。
修正をしました。ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/10/commits/6bc1c865893c50abce67091c38f57880011a0d9a

2022-07-18 23:54 UTC, Takatatsu9 reviewed
Done

2022-07-19 00:15 UTC, konta3291 commented on HitAndBlow/HitAndBlowGame.vb
> +            Dim playerAnswer As String = Main.GetPlayerAnswer
申し訳ございません。
直ってませんでした。
修正しました。ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/10/commits/93d4521e1cf295c4943374dfc1dfca6e61bcc05c

2022-07-19 00:19 UTC, Takatatsu9 reviewed
Done

2022-07-21 00:15 UTC, nabemasamasa approved these changes
LGTM

2022-07-21 00:20 UTC, Takatatsu9 commented
コンフリクトしたので直してくださいね。

手っ取り早いのは、`origin/master`の内容をこのブランチにNonFastFowardMergeする方法でしょう。

2022-07-21 00:23 UTC, konta3291 commented
かしこまりました、コンフリクトを直します。

2022-07-21 00:38 UTC, konta3291 commented
origin/masterをNonFastFowardMergeしコンフリクトを直しました。

2022-07-21 00:44 UTC, Takatatsu9 reviewed
Done

2022-07-21 00:44 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
ひとつ質問いいかな　`<summary>`どこに行った？

2022-07-21 00:52 UTC, konta3291 commented on HitAndBlow/HitAndBlowGame.vb
申し訳ございません、抜けてしまっていました。
もう一度マージし追加します。

2022-07-21 00:52 UTC, konta3291 commented
<summary>が抜けていたため、もう一度マージしました。

2022-07-21 00:55 UTC, Takatatsu9 approved these changes
Done

2022-07-21 00:55 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
>      End Sub
GitHubのDiffだと変なところに変なコードがあるけど、
Gitで差分見ると別に問題無い・・・うーん、なんだこの現象

2022-07-21 05:03 UTC, merged