以前受けた指摘の修正とコンソールアプリからヒット＆ブローを遊べるようにしました。
konta3291/HitAndBlow pull request #3
Opened 2022-07-06 05:05 UTC by konta3291

#### 修正した点
 - ヒットした位置を返すメソッドの処理から「反転させる処理」をメソッド外に移動
 - コーディングルールに則り大文字開始の引数を小文字開始に変更
 - ヒット＆ブローの結果を返す処理を文字列補間式で書く
 - 入力された値が負の値や、四桁でなかった時の処理追加
 - コンピュータの値をランダムに変更
#### 追加した点
 - コンソールアプリで値を受け取りヒット＆ブローの結果を返す
 -  クリアできるまで終われない処理の追加
 - クリア後もう一度遊べるように処理を追加

2022-07-06 05:18 UTC, Takatatsu9 commented
[Q] 以前受けた指摘ってなんですか？

2022-07-06 05:38 UTC, konta3291 commented
ダニエルソフトのリポジトリにプルリクを作ってしまい、そのプルリクに頂いた指摘を修正しfork先のここでプルリクを作り直しました。指摘内容は下記のとおりです。
#### 指摘内容
 - 引数なのに大文字開始になっているところがある
 - ヒット＆ブローの処理をするところに、四桁の整数以外が入るときの処理がない
 - 文字列補間式で書いた方がすっきりするところがある
 - ヒットした位置を返すメソッドで反転させる処理が入っているから罠となっている
 - 出題者の意図することができていない
 以上です。
 指摘を受け追加したコミットは「変数名が大文字開始になっていたので小文字に修正」のコミット以降です。

2022-07-06 06:01 UTC, Takatatsu9 requested changes
Done

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlow.Test.vb
> +End Class
何もしないクラスの作成はなんの価値もないので、このコミットは要らないですね

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlow.Test.vb
> +<TestFixture> Public Class HitAndBlowTest
[MUST] テストクラス名が被クラス名と一致しません。同じにしてください。

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    Public Function ReturnResultOfHitAndBlowGame(playerAnswer As Integer) As String
[IMO] 新しいクラス作って、そこにロジック書いたほうがいいと思います。

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
>      End Sub
ロジック追加したのに遊べないのか・・・

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlow.Test.vb
> +        Assert.AreEqual("Hit:4,Blow:0", result)
[nits] `Assert.AreEqual(expected, actual)`は旧世代の書き方なので、
`Assert.That(actual, Is.EqualTo(expected))`を推奨します。

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    End Function
[Q] テスト書かないんですか？

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    End Function
[Q] テスト書かないんですか？

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    ''' 受け取った2つのリストを比較し、数字が同じであればhitに1を足す
[IMO] メソッドの中身を見ないと「hitに1を足す」の意味がわからないので要再考ですね。
理想は「メソッドの中身を見なくても、メソッド名とコメントを見れば使い方がわかる」です。

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    ''' computerNumberと同じ数字をplayerNumberが持っていればblowに1を足す
[nits] なんかHitのカウントと似たような処理なのにコメントの書き方が変わりすぎじゃない…？

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    End Function
[Q] テスト書かないんですか？

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    End Function
[Q] テスト書かないんですか？

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +        Console.Write(ReturnResultOfHitAndBlowGame(playerNumber))
[MUST] 実際に動作を確認できないのに淡々と動くかもわからないテストも無いロジックを書き連ねられて最後にようやく確認できるのは嫌だ

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +        Else
[MUST] 何もしないIf文に価値はないです。条件を反転させてElseを消しましょう。

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            Throw New ArgumentException("受け取った数値は４桁の整数ではありません")
[Q] これ例外起きたらゲーム強制終了しませんか？

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    End Function
（これかなり最初のほうにあってほしかったなぁ）

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    Public Sub ReturnResultOfHitAndBlowGame(playerAnswer As String)
[IMO] もうReturnしてないからメソッド名変えたほうがいいですね。
というかそもそも`Return～`って何するメソッドなのか全く読み取れないので不適切な名前でしたが

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            HitAndBlow()
[MUST] え？この方法だとメソッド呼び出しが
`HitAndBlow()→ReturnResultOfHitAndBlowGame()→HitAndBlow()→ReturnResultOfHitAndBlowGame()→HitAndBlow()→ReturnResultOfHitAndBlowGame()→HitAndBlow()→ReturnResultOfHitAndBlowGame()→HitAndBlow()→ReturnResultOfHitAndBlowGame()→HitAndBlow()→ReturnResultOfHitAndBlowGame()→HitAndBlow()→ReturnResultOfHitAndBlowGame()→HitAndBlow()→ReturnResultOfHitAndBlowGame()→HitAndBlow()→ReturnResultOfHitAndBlowGame()→HitAndBlow()→ReturnResultOfHitAndBlowGame()→HitAndBlow()→ReturnResultOfHitAndBlowGame()→HitAndBlow()→ReturnResultOfHitAndBlowGame()→…`
ってなりません？この処理順、綺麗ですか？

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            Main()
更にループを重ねるのか・・・

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            Environment.Exit(0)
[Q] 普通にReturnして処理を最後まで走らせて終わりじゃだめなんですか？

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            AskPlayerWantToPlayAgain()
ヒエーッ！循環参照！（前のコミットからそうだったけど）

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> -            Throw New ArgumentException("受け取った数値は４桁の整数ではありません")
例外は例外で正しいんだけどね・・・。`Try`～`Catch`してなかったのが悪かっただけで。

2022-07-06 06:01 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlow.Test.vb
> -    End Sub
> テストできないためテストコードの削除

！！！！？！？？？？？！？！？！？？？？ｗｗｗｗ？？？？！！？？？？🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔

2022-07-06 06:34 UTC, konta3291 commented on HitAndBlowTest/HitAndBlow.Test.vb
> -    End Sub
ReturnResultOfHitAndBlowGame関数をreturnしないメソッドに変更したため、今まで使っていたテストコードが使えなくなってしまい削除しました。また、エラーテストコードも、エラーとしていたところをエラーではなくユーザーにもう一度入力させる処理に変更したので削除しました。
メソッド個々のテストをこれから追加します。

2022-07-06 06:34 UTC, konta3291 commented on HitAndBlow/Main.vb
> -            Throw New ArgumentException("受け取った数値は４桁の整数ではありません")
ご指摘ありがとうございます。
try文で書くようにします。

2022-07-06 06:34 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            AskPlayerWantToPlayAgain()
ご指摘ありがとうございます。
循環参照しないように修正します。

2022-07-06 06:34 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            Environment.Exit(0)
[A]アプリを再起動せずにもう一度遊ぶことができた方が好ましいと考えこのようにしました。
必要ないようなので修正し、処理を最後まで走らせ終了するようにします。

2022-07-06 06:34 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            Main()
ご指摘ありがとうございます。
ループが重ならないように考えなおします。

2022-07-06 06:34 UTC, konta3291 commented on HitAndBlowTest/HitAndBlow.Test.vb
> +        Assert.AreEqual("Hit:4,Blow:0", result)
ご指摘ありがとうございます。
かしこまりました、テストコードに取り入れます。

2022-07-06 06:36 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            HitAndBlow()
ご指摘ありがとうございます。
綺麗な処理順になるようにロジックを考え直します。

2022-07-06 06:37 UTC, konta3291 commented on HitAndBlow/Main.vb
> +    Public Sub ReturnResultOfHitAndBlowGame(playerAnswer As String)
ご指摘ありがとうございます。
適したメソッド名を考え直します。

2022-07-06 06:37 UTC, konta3291 commented on HitAndBlow/Main.vb
> +    End Function
申し訳ありませんでした。

2022-07-06 06:38 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            Throw New ArgumentException("受け取った数値は４桁の整数ではありません")
[A]終了してしまいます。
最新の状態ではユーザーにもう一度入力させる処理にしております。

2022-07-06 06:39 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        Else
ご指摘ありがとうございます。
かしこまりました、修正します。

2022-07-06 06:41 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        Console.Write(ReturnResultOfHitAndBlowGame(playerNumber))
ご指摘ありがとうございます。
テストメソッドを増やします。

2022-07-06 06:42 UTC, konta3291 commented on HitAndBlow/Main.vb
> +    End Function
[A]書きます。申し訳ありませんでした。

2022-07-06 06:42 UTC, konta3291 commented on HitAndBlow/Main.vb
> +    End Function
[A]書きます、申し訳ありませんでした。

2022-07-06 06:43 UTC, konta3291 commented on HitAndBlow/Main.vb
> +    ''' computerNumberと同じ数字をplayerNumberが持っていればblowに1を足す
ご指摘ありがとうございます。
修正します。

2022-07-06 06:44 UTC, konta3291 commented on HitAndBlow/Main.vb
> +    ''' 受け取った2つのリストを比較し、数字が同じであればhitに1を足す
ご指摘ありがとうございます。
かしこまりました、修正します。

2022-07-06 06:44 UTC, konta3291 commented on HitAndBlow/Main.vb
> +    End Function
[A]書きます、申し訳ありませんでした。

2022-07-06 06:44 UTC, konta3291 commented on HitAndBlow/Main.vb
> +    End Function
[A]書きます。申し訳ありませんでした。

2022-07-06 06:44 UTC, konta3291 commented on HitAndBlowTest/HitAndBlow.Test.vb
> +End Class
ご指摘ありがとうございます。
わかりました。

2022-07-06 06:44 UTC, konta3291 commented on HitAndBlowTest/HitAndBlow.Test.vb
> +<TestFixture> Public Class HitAndBlowTest
ご指摘ありがとうございます。
かしこまりました、変更します。

2022-07-06 06:45 UTC, konta3291 commented on HitAndBlow/Main.vb
> +    Public Function ReturnResultOfHitAndBlowGame(playerAnswer As Integer) As String
ご指摘ありがとうございます。
かしこまりました、新しいクラスを作ります。

2022-07-06 06:45 UTC, konta3291 commented on HitAndBlow/Main.vb
>      End Sub
申し訳ありません。
出題者の意図をわかっていませんでした。

2022-07-06 06:51 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
>      End Sub
これは出題者の意図ではないです。開発側のことです。
画面で確認できる機能を1つ追加したら1つコミットを作る（テストが書けるならこれに含める）というのがコミットの目安なんです。

2022-07-06 06:52 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    End Function
回答者はラベル（`[***]`←これ）書かなくていいですよ

2022-07-06 06:58 UTC, konta3291 commented on HitAndBlow/Main.vb
>      End Sub
かしこまりました、意識して作業に取り組みます。

2022-07-06 06:59 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            HitAndBlow()
参考として、メソッドの呼び出しがどうなってるのか軽く説明します
```
Main()
└→HitAndBlow()
￤　￤└→ReturnResultOfHitAndBlowGame()
￤　┌←──┘
┌←─┘
↓
```
と動いてるんですね。なのであの書き方だと
```
Main()
└→HitAndBlow()
￤　￤└→ReturnResultOfHitAndBlowGame()
￤　￤　￤└→HitAndBlow()
￤　￤　￤　￤　└→ReturnResultOfHitAndBlowGame()
￤　￤　￤　￤　￤└→HitAndBlow()
￤　￤　￤　￤　￤　￤　└→ReturnResultOfHitAndBlowGame()
￤　￤　￤　￤　￤　￤　￤└→HitAndBlow()
￤　￤　￤　￤　￤　￤　￤　└→ReturnResultOfHitAndBlowGame()
```
てな形になってしまいます。前のメソッドを呼べば前に戻るわけじゃないんですね。

2022-07-06 07:00 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            Environment.Exit(0)
ツッコミどころはそこじゃないです。複数のメソッドにまたがった循環参照してるとこです。

2022-07-06 07:00 UTC, konta3291 commented on HitAndBlow/Main.vb
> +    End Function
申し訳ありません。存じておりませんでした。今後は書かないようにします。
教えて頂きありがとうございます。

2022-07-06 07:01 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlow.Test.vb
> -    End Sub
コミットする前にテスト動かして、ちゃんと動いてからコミットしましょうね。

2022-07-06 07:09 UTC, Takatatsu9 commented
出題者曰く「クリアできない」

2022-07-06 07:20 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            HitAndBlow()
説明ありがとうございます。
確かにきれいではないですね。説明していただいたことを意識してロジックを考え直します。

2022-07-06 07:21 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            Environment.Exit(0)
かしこまりました、循環参照しないように考えなおします。

2022-07-06 07:21 UTC, konta3291 commented on HitAndBlowTest/HitAndBlow.Test.vb
> -    End Sub
かしこまりました。

2022-07-06 07:25 UTC, konta3291 commented
クリアできない、というのはHit:4,Blow0にならないということでしょうか。
コンピュータ側の数字は四桁、同じ数字を使っても良い仕組みになっていますので、少し難しいと思いますがクリアはできると思います。同じ数字は使わないようにした方がよろしいでしょうか。

2022-07-06 07:34 UTC, Takatatsu9 commented
出題者曰く「全パターンの数字を試してもヒット2ブロー0になった」
出題者曰く「　同　じ　数　字　を　使　っ　て　も　い　い　な　ん　て　仕　様　を　言　っ　た　覚　え　は　な　い　」

2022-07-06 07:48 UTC, konta3291 commented
申し訳ありませんでした。同じ数字は使っても良いように作ってしまいました。
同じ数字は使えないように修正します。

2022-07-06 08:01 UTC, nabemasamasa reviewed
done ( e72aa5c84cfd27b52f2b20185bf05d1df3455a92 まで)

2022-07-06 08:01 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +    ''' 違う場合はもう一度入力させる
メソッドのSummaryに「違う場合はもう一度入力させる」とあるけど、中身では`HitAndBlow`を呼び出してたぶんまたこのVerifyValueを呼び出す……
このメソッドの説明とは違う気がする……

2022-07-06 08:01 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> -            Throw New ArgumentException("受け取った数値は４桁の整数ではありません")
あれ？例外テストを追加したと思ったらConsole.WriteLineになったし、呼び出し元を呼んでる…
例外テストコケるのでは…？タイムアウトなどで……

2022-07-06 23:16 UTC, konta3291 commented on HitAndBlow/Main.vb
> +    ''' 違う場合はもう一度入力させる
ご指摘ありがとうございます。
メソッドに適した説明を考え直します。

2022-07-06 23:21 UTC, konta3291 commented on HitAndBlow/Main.vb
> -            Throw New ArgumentException("受け取った数値は４桁の整数ではありません")
ご指摘ありがとうございます。
コンピュータの数字を固定からランダムに変更したのと、四桁の整数でなかった時はユーザーにもう一度入力を求める処理を追加したので今まで使えていたテストは使えなくなり削除してしまいました。
なのでこれからまたテストを追加します。

2022-07-06 23:31 UTC, nabemasamasa reviewed
done

2022-07-08 04:07 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> -            Throw New ArgumentException("受け取った数値は４桁の整数ではありません")
（ちなみにラベル無しのコメントは独り言なので、指摘ではないし
なんなら返信の必要もないです。返信したいならしてもいいですけど）

2022-07-08 04:12 UTC, konta3291 commented on HitAndBlow/Main.vb
> -            Throw New ArgumentException("受け取った数値は４桁の整数ではありません")
かしこまりました。

2022-07-11 00:04 UTC, konta3291 commented
### 修正点
 - テストクラスの名前を被クラス名に合わせた名前に変更
 - ヒット数とブロー数を返すメソッドのサマリーコメント変更
 - コンピュータ側の四桁の整数の中に同じ数字がないように処理を追加
 - 循環参照していた処理を変更
 - もう一度遊ぶための処理の文言を仕様に合わせ変更
 - ヒット＆ブローの内部的な処理をするクラス作成。Mainモジュールでは画面での処理を行います。

プッシュする前にこちらを投稿するべきでした、申し訳ありません。
見づらいと思いますが変更点の参考になれば幸いです。

2022-07-11 01:23 UTC, konta3291 commented
### 変更点
 - コンピュータの四桁の整数の中に同じ数字がないかテストするテストメソッド追加
 - Assert.AreEqualからAssert.Thatに変更
 - コンピュータの四桁の数字を返すメソッドの、数字を返すかテストしているコードを変更

以上です。ご確認よろしくお願いします。

2022-07-11 01:53 UTC, nabemasamasa requested changes
コーディングルール違反

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowTest.vbproj
> +    <Compile Include="Main.Test.vb" />
クラス名は`MainTest`だけど、ファイル名は`Main.Test.vb`で、乖離しちゃってますね。。。

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlowTest/Main.Test.vb
> +        Assert.AreEqual(result, result)
~~[nits] `Assert.That`の使用をオススメします。より英文法的に正しく(SV＋That節)、acrualとexpectedについて誤解の余地が入りづらいので……
NUnit assert that actual is expected => *NUnitはactualがexpectedであることを検証する*~~

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlowTest/Main.Test.vb
> +        Assert.AreEqual(result, result)
~~[MUST]って、これresultとresultをAssertしてますね！？流石におかしいのでNGです。。。~~

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        While (Regex.IsMatch(playerNumber, "^[0-9]{1,4}$") AndAlso playerNumber.Length = 4) = False
Not使えば良いのでは…？

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        Console.Write("数字を入力してください：")
同じ文言「数字を入力してください：」DRYの余地がありそうです。

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +            Return False
[Q] ? これって、`return playerAnswer.Equals("y")`するのとどう違いますか？

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlow/Main.vb
>          Console.WriteLine("成功です")
~~[Q] インデントズレてませんか？~~

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        Dim play As Boolean = True
Boolean変数……

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        While (playerAnswer.Equals("y") OrElse playerAnswer.Equals("n")) = False
[ヨーダ記法](https://ja.wikipedia.org/wiki/%E3%83%A8%E3%83%BC%E3%83%80%E8%A8%98%E6%B3%95)ってものがありまして。。。。。
空文字を設定しなくても定数.EqualsにすればNullでもエラーなくFalseになってくれます。
他の利点は、上記Wikiを見てみてください。

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +            Console.WriteLine("もう一度プレイしますか？（Y/N）")
[Q] 文言が"Y/N"になってますが、大文字でもちゃんとこのWhile抜けますか？

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlow/HitAndBlow.vbproj
> +    <Compile Include="HitAndBlowGame.vb" />
> ヒット＆ブローのクラス作成。内部的な処理を行います

コミットコメントにはWhyを書いてほしいです……。=> [knowledge/git/Git.beginner.md#コミットコメントのルール](https://github.com/daniel-software-tokyo/knowledge/blob/master/git/Git.beginner.md#%E3%82%B3%E3%83%9F%E3%83%83%E3%83%88%E3%82%B3%E3%83%A1%E3%83%B3%E3%83%88%E3%81%AE%E3%83%AB%E3%83%BC%E3%83%AB)
厳密には`refactoring`はその限りではないんですが、レビュー中に`Next`でこのコミットに飛んで、このコミットコメントでちょっと意図が一目見てわかりかねました……。

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlow/Main.vb
>          Console.WriteLine("成功です")
e7c2a1cde6b09e2af1001006de68cf3f82f33298 で直ってることを確認しました。

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +            Dim HitAndBlowGame As New HitAndBlowGame
[MUST] 変数名は小文字始まり……

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowGame.Test.vb
> +        Assert.AreEqual(result, result)
[MUST] クラスへメソッド抽出されても、ExpectedとActualが一緒のまま……絶対通る

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowGame.Test.vb
> +        Assert.AreEqual(True, numbersThatAreNotDuplicated)
[imo] `Assert.IsTrue`ってメソッドがいます。今回の場合、それが適切かと。

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowGame.Test.vb
> +        Dim result As Char() = HitAndBlowGame.MakeComputerNumber()
[imo] 配列なら、`IEnumerable(Of )`を継承してるはずなので`Distinct()`メソッドが使えるはず。それを使えば、もっとシンプルにできそうです。

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowGame.Test.vb
> +        Dim HitAndBlowGame As New HitAndBlowGame
[nits] 毎回、引数なしでインスタンス生成するなら、いっそPrivate変数化しちゃって`<Setup>`でインスタンス生成しちゃっても良さそうですね。
後、こういうテスト対象クラスの変数名としてよく使われるのが`sut`(SystemUnderTest)って変数名です。
毎回、テスト対象クラスの変数名にするよりは、短いですしたった三文字で意味も通じるのでオススメです。

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowGame.Test.vb
> +        Assert.That(True, [Is].EqualTo(IsNumeric(New String(result))))
あ、Assert.Thatにする過程で一緒にresultしか与えてない問題も直ってる…
けど、テストメソッド名にある、`4桁かどうか`はテストしてない……

2022-07-11 01:53 UTC, nabemasamasa commented on HitAndBlowTest/Main.Test.vb
> +        Assert.AreEqual(result, result)
b0386ca4149585e7a4577a4778fc6edb1572bc80 で解消されている事は確認しました……が、まだ一点だけもんにょり

2022-07-11 01:54 UTC, nabemasamasa commented on HitAndBlowTest/Main.Test.vb
> +        Assert.AreEqual(result, result)
あ、解決済みなのに削除してませんでした、失礼しました。

2022-07-11 01:56 UTC, nabemasamasa commented on HitAndBlowTest/HitAndBlowGame.Test.vb
> +        Assert.AreEqual(result, result)
b0386ca4149585e7a4577a4778fc6edb1572bc80 で解消されている事は確認しました……が、まだ一点だけもんにょり

2022-07-11 02:11 UTC, konta3291 commented on HitAndBlowTest/Main.Test.vb
> +        Assert.AreEqual(result, result)
ご指摘ありがとうございます。
「まだ一点だけ」というのは、四桁で返すかのテストのことでしょうか。
四桁で返すかのテストは別のテストメソッドで行っております。

2022-07-11 04:06 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGame.Test.vb
> +        Assert.That(True, [Is].EqualTo(IsNumeric(New String(result))))
ご指摘ありがとうございます。
四桁であるテストは別のテストメソッドで行っていますので、テストメソッド名を修正します。

2022-07-11 04:06 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGame.Test.vb
> +        Dim HitAndBlowGame As New HitAndBlowGame
ご指摘ありがとうございます。
かしこまりました、修正します。

2022-07-11 04:06 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGame.Test.vb
> +        Dim result As Char() = HitAndBlowGame.MakeComputerNumber()
ご指摘ありがとうございます。
かしこまりました、調べて取り入れます。

2022-07-11 04:07 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGame.Test.vb
> +        Assert.AreEqual(True, numbersThatAreNotDuplicated)
ご指摘ありがとうございます。
かしこまりました、Assert.IsTrueメソッドを取り入れます。

2022-07-11 04:07 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            Dim HitAndBlowGame As New HitAndBlowGame
ご指摘ありがとうございます。
申し訳ありません、修正します。

2022-07-11 04:07 UTC, konta3291 commented on HitAndBlow/HitAndBlow.vbproj
> +    <Compile Include="HitAndBlowGame.vb" />
ご指摘ありがとうございます。
かしこまりました、今後はWhyに意識してコミットコメントを考えます
ありがとうございます。

2022-07-11 04:07 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            Console.WriteLine("もう一度プレイしますか？（Y/N）")
ご指摘ありがとうございます。
大文字だとWhile文は抜けませんでした。
大文字でしか抜けないように修正します。

2022-07-11 04:07 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        While (playerAnswer.Equals("y") OrElse playerAnswer.Equals("n")) = False
ご指摘ありがとうございます。
かしこまりました、ヨーダ記法を調べ取り入れます。

2022-07-11 04:07 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        Dim play As Boolean = True
ご指摘ありがとうございます。
変数名が適していないといことでしょうか。

2022-07-11 04:07 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            Return False
ご指摘ありがとうございます。
挙動は変わらないです。
無駄なIF文を書いていたことになりますので修正します、ありがとうございます。

2022-07-11 04:07 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        Console.Write("数字を入力してください：")
ご指摘ありがとうございます。
かしこまりました、DRYについて調べ取り入れます。

2022-07-11 04:07 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        While (Regex.IsMatch(playerNumber, "^[0-9]{1,4}$") AndAlso playerNumber.Length = 4) = False
ご指摘ありがとうございます。
Notに変更します。

2022-07-11 04:07 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowTest.vbproj
> +    <Compile Include="Main.Test.vb" />
ご指摘ありがとうございます。
修正します。

2022-07-11 04:27 UTC, Takatatsu9 approved these changes
Done

2022-07-11 04:27 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +        While (Regex.IsMatch(playerNumber, "^[0-9]{1,4}$") AndAlso playerNumber.Length = 4) = False
なぜそうなのかを一切考えず、言われたからやるっていうのはやめてくださいね。

@nabemasamasa 
このコミットは循環参照の廃止が目的なので、If何もしないElseの修正自体
無かったことにして今の形が正解でいいと思います

2022-07-11 04:27 UTC, Takatatsu9 commented on HitAndBlow/HitAndBlowGame.vb
> +            Main.ShowHitAndBlowResult(hit, blow)
> ヒット＆ブローの結果を表示する処理をMainモジュールに移動

やった内容じゃなくやった意図を書いて…

2022-07-11 04:43 UTC, nabemasamasa commented on HitAndBlow/Main.vb
> +        Dim play As Boolean = True
Booleanなら変数名は、三単現か形容詞、もしくは例外的に許可している単語のみ、ですね。
[knowledge/VB.NET.コーディングルール.md#22-boolean変数](https://github.com/daniel-software-tokyo/knowledge/blob/master/VB.NET.%E3%82%B3%E3%83%BC%E3%83%87%E3%82%A3%E3%83%B3%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%AB.md#22-boolean%E5%A4%89%E6%95%B0)

2022-07-11 04:45 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +        While (Regex.IsMatch(playerNumber, "^[0-9]{1,4}$") AndAlso playerNumber.Length = 4) = False
（さっきつけたコメント読んでたら気にしないで）

2022-07-11 04:55 UTC, nabemasamasa commented on HitAndBlowTest/Main.Test.vb
> +        Assert.AreEqual(result, result)
テストクラスのネストを使ってグルーピングすれば、「〇〇のメソッドがXXXXするテスト」じゃなくて「XXXXするテスト」で縮めて書けるんじゃないか？ってことをペアプロして教えました。
(という周知・共有です)

2022-07-11 05:07 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +        Console.Write("数字を入力してください：")
わからないならここで聞き返していいのよ

2022-07-11 05:20 UTC, konta3291 commented on HitAndBlow/HitAndBlowGame.vb
> +            Main.ShowHitAndBlowResult(hit, blow)
ご指摘ありがとうございます。
かしこまりました、内容を書くことを意識してコミットコメントを考えます。

2022-07-11 05:21 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        Dim play As Boolean = True
かしこまりました、コーディングルールに則った変数名に修正します。

2022-07-11 05:21 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        Console.Write("数字を入力してください：")
かしこまりました、ありがとうございます。
調べてわからなければ、ここで質問させていただきます。
よろしくお願いします。

2022-07-12 01:12 UTC, konta3291 commented
### 修正点
 - コーディングルール違反をしていたところの修正（変数名、プロジェクト名）
 - テストメソッドをグルーピング
 - テストメソッドの処理をシンプルに
 - もう一度遊ぶか聞く処理の修正
    - y,nでしかwhile文を抜けられなかったところをY,Nに変更
    - return playerAnswer.Equals("y")に変更
  - whileの条件に＝falseとなっていたのをNotに変更
  - boolean変数playの名前を変更
  - ヨーダ記法を取り入れる
  - 数字を入力してくださいを二回書いていたので一回だけ書くように変更

以上です。お手すきの際にでもご確認よろしくお願いします。

2022-07-12 01:55 UTC, Takatatsu9 requested changes
Done

2022-07-12 01:55 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +            Assert.That(result, [Is].EqualTo(notDuplicatNumber))
[IMO] 検証したい値同士を使って比較してるのが違和感。
`Assert.That(actual.Length, [Is].EqualTo(4))` みたいに、`expected`の値は固定値がいいかな

2022-07-12 01:55 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +                Exit While
[IMO] うーん、34行目と37行目で条件式がダブってしまった
なるほど…　このロジックは1回の判定で十分なんだな

2022-07-12 01:55 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        Private result As Char()
> テスト対象メソッドが引数なしで呼び出されている処理が複数あり、Setupで一つの呼び出しにまとめることが可能なのでまとめました

[MUST] コミットの変化点の説明において過去形は禁止です。
過去形を使っていいのは過去のコミットに対してのみです。
「コミットコメントの後に同コミットのDiffの内容が適用される」という順番でお考え下さい。

2022-07-12 01:55 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    Private sut As New HitAndBlowGame
> テストメソッドのインスタンスを共有できるようにPrivateで宣言

これ1つ前のコミットに含めたほうがいいやつ…

2022-07-12 01:56 UTC, Takatatsu9 commented
修正点リストアップされてもどの指摘に対しての修正かわからないので
指摘のコメントに対して修正しましたと書き込んでください。
できればどのコミットがその修正なのかも添えるとヨシ

2022-07-12 02:48 UTC, konta3291 commented
かしこまりました。

2022-07-12 02:48 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    Private sut As New HitAndBlowGame
ご指摘ありがとうございます。
ローカルリポジトリにて、このコミットの内容を前のコミットに含め、強制Pushしようと考えているのですが
あまりよくない手段でしょうか。
教えて頂けると幸いです。

2022-07-12 02:48 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        Private result As Char()
ご指摘ありがとうございます。
かしこまりました、コミットコメントを変更します。

2022-07-12 02:48 UTC, konta3291 commented on HitAndBlow/Main.vb
> +                Exit While
ご指摘ありがとうございます。
条件式がダブらないようにロジックを考え直します。

2022-07-12 02:48 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +            Assert.That(result, [Is].EqualTo(notDuplicatNumber))
ご指摘ありがとうございます。
かしこまりました、変更します。

2022-07-12 03:02 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    Private sut As New HitAndBlowGame
我々は、まだレビュー中の人がいるかで判断しています。
Pushしたてでまだ誰もレビューしてなさそうならforce-pushしちゃえーってやりますし、
今レビューしてる人が居そうならば完了するまで待ちますね。

2022-07-12 04:07 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    Private sut As New HitAndBlowGame
ご回答ありがとうございます。
かしこまりました、force-pushしようと考えているのですが、レビューは完了されていますか？

2022-07-12 04:22 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    Private sut As New HitAndBlowGame
はい。Doneとつけたので終わっています。まだ途中の場合、コメントしていないか、
あるいは「Done (`コミットハッシュ` まで)」と書いています。

2022-07-12 04:25 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    Private sut As New HitAndBlowGame
かしこまりました、ご回答ありがとうございます。

2022-07-12 04:46 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        Private result As Char()
コミットコメントを変更しました。コミットは下記の通りです。
https://github.com/konta3291/HitAndBlow/pull/3/commits/dd6beefbcb80bcb195289d50897a2f9dc9d2340b

2022-07-12 04:47 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +    Private sut As New HitAndBlowGame
前のコミットに内容を含めました。コミットは下記の通りです。
https://github.com/konta3291/HitAndBlow/pull/3/commits/dd6beefbcb80bcb195289d50897a2f9dc9d2340b

2022-07-12 05:14 UTC, Takatatsu9 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        Private result As Char()
> テストメソッドの処理をシンプルにすることが可能だったので、引数を渡さないで呼び出しているメソッドをSetupメソッドに入れ、インスタンスをPrivateで宣言する処理に変更

なっが・・・。
ついこの前やった事じゃなくやった意図を書いてと言ったばかりですよね。
それを元にこのコメントを直すとこうなります

> テストメソッドの処理をシンプルにすることが可能

2022-07-12 05:25 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        Private result As Char()
ご指摘ありがとうございます。
申し訳ありません、修正します。

2022-07-12 06:07 UTC, Takatatsu9 approved these changes
Done
わかりやすく適切なコミットコメント 👍

2022-07-12 06:07 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            Dim count As Integer
わざわざカウンター持たせる必要無い書き方もあるけど・・・まあ、今はこれでいいか。

2022-07-12 06:09 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +            Assert.That(result, [Is].EqualTo(notDuplicatNumber))
修正しました。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/86d2331847ecd3840985f0c62d8735f09542c995
お手すきの際にでもご確認よろしくお願いします。

2022-07-12 06:09 UTC, konta3291 commented on HitAndBlow/Main.vb
> +                Exit While
条件式のダブりをなくしました。
修正コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/73e7db6dd1ecf943c3356580b8c94df5818e861b
お手すきの際にでもご確認よろしくお願いします。

2022-07-12 06:09 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGameTest.vb
> +        Private result As Char()
コミットコメント変更しました。
指摘を受けたのにもかかわらず、適したコミットコメントができていなく申し訳ありません。
修正コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/b2d642597bf1ab0911def807a6fa5df1ee384fd2
お手すきの際にでもご確認よろしくお願いします。

2022-07-12 06:17 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            Dim count As Integer
カウンターを持たせる必要のない書き方を考えてみます。

2022-07-12 07:36 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowTest.vbproj
> +    <Compile Include="Main.Test.vb" />
修正しました。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/4550381835429e4be9984a047ff9ec5e3ea17e51
お手すきの際にでもご確認よろしくお願いします。

2022-07-12 07:36 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        While (Regex.IsMatch(playerNumber, "^[0-9]{1,4}$") AndAlso playerNumber.Length = 4) = False
修正しました。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/2036a0566a7acd55380939117063687799ec532a
お手すきの際にでもご確認よろしくお願いします。

2022-07-12 07:36 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        Console.Write("数字を入力してください：")
変更しました。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/878bca032dbd00a301ae8e78f1a43d7a83bc1f0d
お手すきの際にでもご確認よろしくお願いします。

2022-07-12 07:37 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            Return False
変更しました。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/1d1186d090f1bc167006345885adb7ea8b6a1025
お手すきの際にでもご確認よろしくお願いします。

2022-07-12 07:37 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        Dim play As Boolean = True
変更しました。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/dfcf4e70d7f3a592550bf99ac208ef35949e3604
お手すきの際にでもご確認よろしくお願いします。

2022-07-12 07:37 UTC, konta3291 commented on HitAndBlow/Main.vb
> +        While (playerAnswer.Equals("y") OrElse playerAnswer.Equals("n")) = False
変更しました。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/9c6768d353a6156b433858f51749689eec4f1553
お手すきの際にでもご確認よろしくお願いします。

2022-07-12 07:37 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            Console.WriteLine("もう一度プレイしますか？（Y/N）")
修正しました。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/7e88a8cf77c05804dd5122920bb51eeff12fcd0d
お手すきの際にでもご確認よろしくお願いします。

2022-07-12 07:38 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            Dim HitAndBlowGame As New HitAndBlowGame
修正しました。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/39958733950197003ebdb01e315d2e217d3ec3e0
お手すきの際にでもご確認よろしくお願いします。

2022-07-12 07:38 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGame.Test.vb
> +        Assert.AreEqual(True, numbersThatAreNotDuplicated)
変更しました。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/2288a6abbb24074269db9449a9d0edefd238c69f
お手すきの際にでもご確認よろしくお願いします。

2022-07-12 07:38 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGame.Test.vb
> +        Dim result As Char() = HitAndBlowGame.MakeComputerNumber()
修正しました。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/77b82559bf9377647aa65a993d2b8238cf0b9527
お手すきの際にでもご確認よろしくお願いします。

2022-07-12 07:38 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGame.Test.vb
> +        Dim HitAndBlowGame As New HitAndBlowGame
修正しました。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/b2d642597bf1ab0911def807a6fa5df1ee384fd2
お手すきの際にでもご確認よろしくお願いします。

2022-07-12 07:38 UTC, konta3291 commented on HitAndBlowTest/HitAndBlowGame.Test.vb
> +        Assert.That(True, [Is].EqualTo(IsNumeric(New String(result))))
テストメソッド名変更しました。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/d5753f87216922e09285e043e566884896058c00
お手すきの際にでもご確認よろしくお願いします。

2022-07-13 00:42 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            Dim count As Integer
カウンターを持たせない処理に変更しました。
「カウンター持たせる必要の無い書き方」はこちらでしょうか。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/b6aa310409d47af7ed9bfbb574e87a594386e118
ご確認よろしくお願いします。

2022-07-13 00:48 UTC, Takatatsu9 reviewed
Done

2022-07-13 00:48 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            End If
これint型がbool型になっただけでやってること完全に一緒ですよね？

2022-07-13 00:54 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            End If
ご指摘ありがとうございます。
はい、やっていることは一緒です。無駄なコミットをしてしまい申し訳ございません。
考え直し修正します。

2022-07-13 01:17 UTC, nabemasamasa reviewed
done

2022-07-13 01:32 UTC, Takatatsu9 reviewed
Done

2022-07-13 01:32 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            If Regex.IsMatch(playerNumber, "^[0-9]{1,4}$") AndAlso playerNumber.Length = 4 Then
大体想像してた形になりましたね。

[IMO] `While True`は使い方を誤ると危険なため、
抜ける条件となるこいつをメソッド化してテストするとより良いです。

2022-07-13 02:31 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            If Regex.IsMatch(playerNumber, "^[0-9]{1,4}$") AndAlso playerNumber.Length = 4 Then
ご指摘ありがとうございます。
メソッド化し、テストも追加しました。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/611133b852172a59163551a382f5ea4582d9cfb8
ご確認よろしくお願いします。

2022-07-13 03:02 UTC, Takatatsu9 requested changes
Done

2022-07-13 03:02 UTC, Takatatsu9 commented on HitAndBlowTest/MainTest.vb
> +        <Test()> Public Sub 四桁の数字を渡したときのテスト()
[MUST] 何が正しい動きなのか全くわからないテスト名

2022-07-13 03:02 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +    Public Function IsNumbersAreCorrectForGame(number As String) As Boolean
[MUST] Publicはコメント必須

2022-07-13 04:24 UTC, konta3291 commented on HitAndBlow/Main.vb
> +    Public Function IsNumbersAreCorrectForGame(number As String) As Boolean
ご指摘ありがとうございます。
コメントを追加しました。下記のコミットからご確認よろしくお願いします。
https://github.com/konta3291/HitAndBlow/pull/3/commits/9b3594e55f597f2b4018db49e1270c21895dcad1

2022-07-13 04:24 UTC, konta3291 commented on HitAndBlowTest/MainTest.vb
> +        <Test()> Public Sub 四桁の数字を渡したときのテスト()
ご指摘ありがとうございます。
修正しました、下記のコミットからご確認よろしくお願いします。
https://github.com/konta3291/HitAndBlow/pull/3/commits/c143e1b9e592a8b9e2eb8380dca0c8a47af5bf63

2022-07-13 05:25 UTC, Takatatsu9 approved these changes
Done

2022-07-13 05:25 UTC, Takatatsu9 commented on HitAndBlowTest/MainTest.vb
> +        <Test()> Public Sub 四桁の数字を渡したときはTrueと返すかテスト()
`と返すかテスト`は要らないですね

2022-07-13 05:37 UTC, konta3291 commented on HitAndBlowTest/MainTest.vb
> +        <Test()> Public Sub 四桁の数字を渡したときはTrueと返すかテスト()
ご指摘ありがとうございます。
かしこまりました。
修正しました、ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/fc5e51d33849a36c185a9860a165deee69702d18

2022-07-13 05:39 UTC, Takatatsu9 reviewed
Done

2022-07-13 23:30 UTC, nabemasamasa approved these changes
Done 👍

2022-07-13 23:43 UTC, Takatatsu9 commented
出題者曰く「リトライ時に入力する文字の位置がイメージと違う」「リトライできない」

2022-07-14 00:14 UTC, konta3291 commented
> 出題者曰く「リトライ時に入力する文字の位置がイメージと違う」「リトライするか聞くところから先に進まない」

かしこまりました、文言を修正しました。ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/d64f6c295d205f8b41eae32ed84e47943f58416b

2022-07-14 00:19 UTC, Takatatsu9 reviewed
Done

2022-07-14 00:19 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
>          End While
これなら
```
Do
    'メイン処理
Loop While AskPlayerWantToPlayAgain()
```
という書き方で`isPlayerWantsToPlay `なくせますね

2022-07-14 00:26 UTC, konta3291 commented on HitAndBlow/Main.vb
>          End While
ご指摘ありがとうございます。
気づかなかったです、ありがとうございます。
修正します。

2022-07-14 00:36 UTC, konta3291 commented on HitAndBlow/Main.vb
>          End While
修正しました。
ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/dc88586406dfe2a0d179ef9f61fbfe66d8645d83

2022-07-14 00:45 UTC, Takatatsu9 reviewed
Done

2022-07-14 03:08 UTC, Takatatsu9 reviewed
Done

2022-07-14 03:08 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> +            Console.Write("もう一度プレイしますか？（Y/N）:")
[IMO] わざわざ大文字と小文字両方見るんじゃなくて、入力値をどっちかに統一しちゃえばいい

2022-07-14 03:08 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> -        While Not ("Y".Equals(playerAnswer) OrElse "N".Equals(playerAnswer))
> リプレイ処理を仕様に合わせた処理に変更

[IMO] よくないコミットコメント
Q. なぜこの変更を加えたのですか？
A. 仕様だからです。
Q. 仕様とはなんですか？
A. 仕様ということです。

2022-07-14 04:06 UTC, konta3291 commented on HitAndBlow/Main.vb
> -        While Not ("Y".Equals(playerAnswer) OrElse "N".Equals(playerAnswer))
ご指摘ありがとうございます。
適したコミット名に修正します。

2022-07-14 04:07 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            Console.Write("もう一度プレイしますか？（Y/N）:")
ご指摘ありがとうございます。
かしこまりました、修正します。

2022-07-14 04:21 UTC, konta3291 commented on HitAndBlow/Main.vb
> -        While Not ("Y".Equals(playerAnswer) OrElse "N".Equals(playerAnswer))
コミット名を修正しました。
ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/b88cc27a3ced1aaff13198449bb35d7e60411158

2022-07-14 04:42 UTC, konta3291 commented on HitAndBlow/Main.vb
> +            Console.Write("もう一度プレイしますか？（Y/N）:")
大文字に統一するように修正しました。
ご確認よろしくお願いします。
コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/8d7e86284f5781209338e52e162a1a8ff94a8f3b

2022-07-14 05:24 UTC, Takatatsu9 reviewed
Done

2022-07-14 05:24 UTC, Takatatsu9 commented on HitAndBlow/Main.vb
> -        While Not ("Y".Equals(playerAnswer) OrElse "N".Equals(playerAnswer))
> リプレイ処理で受け付ける入力文字を仕様に合わせて追加

もしかして
Q. 仕様とはなんですか？
A. 仕様ということです。
が通じると思いました？もしこの開発が数年続くと仮定して、
このコミットコメントを読んだときにわざわざ当時の仕様書を
探し出して仕様が書かれている部分を見つけろと言いたいのですか？

2022-07-14 05:43 UTC, konta3291 commented on HitAndBlow/Main.vb
> -        While Not ("Y".Equals(playerAnswer) OrElse "N".Equals(playerAnswer))
わかりづらいコミットコメントをしてしまい申し訳ございませんでした。
コミットコメントを修正しました。
ご確認よろしくお願いします。コミットはこちらです：https://github.com/konta3291/HitAndBlow/pull/3/commits/6fce2fba6376597faddd617c3b619758324f6173

2022-07-14 06:04 UTC, Takatatsu9 reviewed
Done

2022-07-14 23:27 UTC, nabemasamasa reviewed
Done

2022-07-15 02:33 UTC, closed without merging